# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: devise_duo 1.5.3 ruby lib

Gem::Specification.new do |s|
  s.name = "devise_duo"
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["David John"]
  s.date = "2015-10-20"
  s.description = "Duo plugin for Devise"
  s.email = "dj@dbjohn.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "app/assets/javascripts/devise_duo.js",
    "app/assets/stylesheets/devise_duo.css",
    "app/assets/stylesheets/devise_duo.sass",
    "app/controllers/devise/devise_duo_controller.rb",
    "app/controllers/devise_duo/passwords_controller.rb",
    "app/views/devise/enable_duo.html.erb",
    "app/views/devise/enable_duo.html.haml",
    "app/views/devise/verify_duo.html.erb",
    "app/views/devise/verify_duo.html.haml",
    "app/views/devise/verify_duo_installation.html.erb",
    "app/views/devise/verify_duo_installation.html.haml",
    "config/locales/en.yml",
    "devise_duo.gemspec",
    "lib/devise_duo.rb",
    "lib/devise_duo/controllers/helpers.rb",
    "lib/devise_duo/controllers/view_helpers.rb",
    "lib/devise_duo/hooks/duo_authenticatable.rb",
    "lib/devise_duo/mapping.rb",
    "lib/devise_duo/models/duo_authenticatable.rb",
    "lib/devise_duo/models/duo_lockable.rb",
    "lib/devise_duo/rails.rb",
    "lib/devise_duo/routes.rb",
    "lib/generators/active_record/devise_duo_generator.rb",
    "lib/generators/active_record/templates/migration.rb",
    "lib/generators/devise_duo/devise_duo_generator.rb",
    "lib/generators/devise_duo/install_generator.rb",
    "spec/controllers/devise_duo_controller_spec.rb",
    "spec/controllers/passwords_controller_spec.rb",
    "spec/features/duo_authenticatable_spec.rb",
    "spec/features/duo_lockable_spec.rb",
    "spec/generators_spec.rb",
    "spec/models/duo_authenticatable_spec.rb",
    "spec/models/duo_lockable_spec.rb",
    "spec/orm/active_record.rb",
    "spec/rails-app/Gemfile",
    "spec/rails-app/Gemfile.lock",
    "spec/rails-app/Rakefile",
    "spec/rails-app/app/assets/images/rails.png",
    "spec/rails-app/app/assets/javascripts/application.js",
    "spec/rails-app/app/assets/javascripts/devise_duo.js",
    "spec/rails-app/app/assets/javascripts/welcome.js",
    "spec/rails-app/app/assets/stylesheets/application.css",
    "spec/rails-app/app/assets/stylesheets/devise_duo.css",
    "spec/rails-app/app/assets/stylesheets/welcome.css.scss",
    "spec/rails-app/app/controllers/application_controller.rb",
    "spec/rails-app/app/controllers/welcome_controller.rb",
    "spec/rails-app/app/helpers/application_helper.rb",
    "spec/rails-app/app/helpers/welcome_helper.rb",
    "spec/rails-app/app/mailers/.gitkeep",
    "spec/rails-app/app/models/.gitkeep",
    "spec/rails-app/app/models/lockable_user.rb",
    "spec/rails-app/app/models/user.rb",
    "spec/rails-app/app/views/devise/devise_duo/enable_duo.html.erb",
    "spec/rails-app/app/views/devise/devise_duo/verify_duo.html.erb",
    "spec/rails-app/app/views/devise/devise_duo/verify_duo_installation.html.erb",
    "spec/rails-app/app/views/layouts/application.html.erb",
    "spec/rails-app/app/views/welcome/index.html.erb",
    "spec/rails-app/config.ru",
    "spec/rails-app/config/application.rb",
    "spec/rails-app/config/boot.rb",
    "spec/rails-app/config/database.yml",
    "spec/rails-app/config/environment.rb",
    "spec/rails-app/config/environments/development.rb",
    "spec/rails-app/config/environments/production.rb",
    "spec/rails-app/config/environments/test.rb",
    "spec/rails-app/config/initializers/duo.rb",
    "spec/rails-app/config/initializers/backtrace_silencers.rb",
    "spec/rails-app/config/initializers/devise.rb",
    "spec/rails-app/config/initializers/inflections.rb",
    "spec/rails-app/config/initializers/mime_types.rb",
    "spec/rails-app/config/initializers/secret_token.rb",
    "spec/rails-app/config/initializers/session_store.rb",
    "spec/rails-app/config/initializers/wrap_parameters.rb",
    "spec/rails-app/config/locales/devise.duo.en.yml",
    "spec/rails-app/config/locales/devise.en.yml",
    "spec/rails-app/config/locales/en.yml",
    "spec/rails-app/config/routes.rb",
    "spec/rails-app/db/development.sqlite3",
    "spec/rails-app/db/migrate/20130419164907_devise_create_users.rb",
    "spec/rails-app/db/migrate/20130419164936_devise_duo_add_to_users.rb",
    "spec/rails-app/db/schema.rb",
    "spec/rails-app/db/seeds.rb",
    "spec/rails-app/lib/assets/.gitkeep",
    "spec/rails-app/lib/tasks/.gitkeep",
    "spec/rails-app/public/404.html",
    "spec/rails-app/public/422.html",
    "spec/rails-app/public/500.html",
    "spec/rails-app/public/favicon.ico",
    "spec/rails-app/public/robots.txt",
    "spec/rails-app/script/rails",
    "spec/routing/routes_spec.rb",
    "spec/spec_helper.rb",
    "spec/support/helpers.rb"
  ]
  s.homepage = "https://github.com/duo/duo-devise"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.4.3"
  s.summary = "Duo plugin for Devise"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<devise>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<yard>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, [">= 0"])
      s.add_development_dependency(%q<bundler>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 2.0.1"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
      s.add_development_dependency(%q<sass-rails>, [">= 0"])
      s.add_development_dependency(%q<jquery-rails>, [">= 0"])
      s.add_development_dependency(%q<pry>, [">= 0"])
    else
      s.add_dependency(%q<devise>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<yard>, [">= 0"])
      s.add_dependency(%q<rdoc>, [">= 0"])
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 2.0.1"])
      s.add_dependency(%q<simplecov>, [">= 0"])
      s.add_dependency(%q<sass-rails>, [">= 0"])
      s.add_dependency(%q<jquery-rails>, [">= 0"])
      s.add_dependency(%q<pry>, [">= 0"])
    end
  else
    s.add_dependency(%q<devise>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<yard>, [">= 0"])
    s.add_dependency(%q<rdoc>, [">= 0"])
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 2.0.1"])
    s.add_dependency(%q<simplecov>, [">= 0"])
    s.add_dependency(%q<sass-rails>, [">= 0"])
    s.add_dependency(%q<jquery-rails>, [">= 0"])
    s.add_dependency(%q<pry>, [">= 0"])
  end
end

